# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[
        (r'E:\MySelf\Code\python_git\micro_app\app\wechat_ui_pyside\venv\Lib\site-packages\pyzbar\libiconv.dll', 'pyzbar'),
        (r'E:\MySelf\Code\python_git\micro_app\app\wechat_ui_pyside\venv\Lib\site-packages\pyzbar\libzbar-64.dll', 'pyzbar'),
        (r'E:\MySelf\Code\python_git\micro_app\app\wechat_ui_pyside\venv\Lib\site-packages\pyzbar\libiconv.dll', 'pyzbar'),
        (r'E:\MySelf\Code\python_git\micro_app\app\wechat_ui_pyside\venv\Lib\site-packages\pyzbar\libzbar-64.dll', 'pyzbar'),
    ],
    datas=[
        ('components', 'components'),
        ('styles', 'styles'),
        ('utils', 'utils'),
        ('config', 'config'),
        ('images', 'images'),
        ('docs', 'docs'),
    ],
    hiddenimports=[
        # PySide6 完整导入
        'PySide6',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtNetwork',
        'PySide6.QtOpenGL',
        'PySide6.QtSvg',
        'PySide6.QtSql',
        'PySide6.QtPrintSupport',
        'shiboken6',
        
        # Pillow 完整导入
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'PIL.ImageFilter',
        'PIL.ImageEnhance',
        'PIL.ImageOps',
        'PIL.ImageChops',
        'PIL.ImageColor',
        'PIL.ImageFile',
        'PIL.ImageGrab',
        'PIL.ImagePath',
        'PIL.ImageSequence',
        'PIL.ImageStat',
        'PIL.ImageTransform',
        'PIL.ImageWin',
        'PIL._imaging',
        'PIL._imagingmath',
        'PIL._imagingmorph',
        'PIL._imagingft',
        'PIL._webp',
        
        # QR 码相关
        'qrcode',
        'qrcode.image',
        'qrcode.image.pil',
        'qrcode.image.svg',
        'qrcode.constants',
        'qrcode.util',
        
        # 应用模块 - 完整路径导入
        'components',
        'components.base_content',
        'components.header',
        'components.nav_primary',
        'components.nav_secondary',
 
        'components.content_area',
        'components.settings_dialog',
        'components.tools',
        'components.tools.contact',
        'components.tools.json_formatter',
        'components.tools.encode_decode',
        'components.tools.file_search',
        'components.tools.image_conver',
        'components.tools.regex_formatter',
        'components.tools.file_diff',
        'components.tools.code_formatter',
        'components.tools.base_converter',
        'components.tools.color_picker',
        'components.tools.media_download',
        'components.tools.qr_tool',
        'components.tools.screen_shot',
        
        # 样式模块
        'styles',
        'styles.constants',
        'styles.constants_dark',
        'styles.widgets',
        'styles.factory',
        'styles.generator',
        
        # 工具模块
        'utils',
        'utils.api_client',
        'utils.background_api',
        'utils.http_client',
        'utils.image_loader',
        'utils.logger',
        
        # 配置模块
        'config',
        'config.app_config',
        'config.nav_config',
        
        # 网络和请求相关
        'requests',
        'requests.adapters',
        'requests.auth',
        'requests.cookies',
        'requests.exceptions',
        'requests.models',
        'requests.sessions',
        'requests.structures',
        'requests.utils',
        'urllib3',
        'urllib3.util',
        'urllib3.util.ssl_',
        'urllib3.util.retry',
        'urllib3.poolmanager',
        'urllib3.connection',
        'urllib3.connectionpool',
        'certifi',
        
        # 标准库
        'ssl',
        'json',
        'hashlib',
        'base64',
        'binascii',
        'codecs',
        'html',
        'html.parser',
        'xml',
        'xml.etree',
        'xml.etree.ElementTree',
        're',
        'threading',
        'queue',
        'time',
        'datetime',
        'logging',
        'logging.handlers',
        'pathlib',
        'os',
        'sys',
        'platform',
        'socket',
        'uuid',
        'tempfile',
        'shutil',
        'subprocess',
        'ctypes',
        'ctypes.util',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'IPython',
        'jupyter',
        'notebook',
        '_pytest',
        'pytest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='KiwiKit',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,  # 禁用 UPX 压缩避免 DLL 问题和误报
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # 必须是 False，避免控制台窗口
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='images/icon.ico' if os.path.exists('images/icon.ico') else None,
    version='version_info.txt',  # 添加版本信息减少误报
)
